-- PAÍS
CREATE TABLE TB_PAIS (
  COD_PAIS    NUMERIC(4)       SERIAL PRIMARY KEY,
  NOME_PAIS   VARCHAR(60)     NOT NULL,
  SIGLA_PAIS  CHAR(2)          NOT NULL,
  CONSTRAINT UK_TB_PAIS_SIGLA UNIQUE (SIGLA_PAIS)
);

-- FABRICANTE
CREATE TABLE TB_FABRICANTE (
  COD_FABRICANTE   NUMERIC(6)      SERIAL PRIMARY KEY,
  NOME_FABRICANTE  VARCHAR(80)   NOT NULL,
  COD_PAIS_SEDE    NUMERIC(4)      NOT NULL,
  CONSTRAINT UK_TB_FABRICANTE_NOME UNIQUE (NOME_FABRICANTE),
  CONSTRAINT FK_FABRICANTE_PAIS FOREIGN KEY (COD_PAIS_SEDE)
    REFERENCES TB_PAIS (COD_PAIS)
);

-- MODELO (define se é nacional/importado via país de produção)
CREATE TABLE TB_MODELO (
  COD_MODELO          NUMERIC(8)     SERIAL PRIMARY KEY,
  NOME_MODELO         VARCHAR(80)  NOT NULL,
  COD_FABRICANTE      NUMERIC(6)     NOT NULL,
  COD_PAIS_PRODUCAO   NUMERIC(4)     NOT NULL,
  SEGMENTO            VARCHAR(30)  NOT NULL,
  TIPO_COMBUSTIVEL    VARCHAR(20)  NOT NULL,
  ANO_INICIO          NUMERIC(4)     NOT NULL,
  FL_NACIONAL         CHAR(1)       NOT NULL,
  CONSTRAINT CK_TB_MODELO_FLN CHECK (FL_NACIONAL IN ('S','N')),
  CONSTRAINT FK_MODELO_FABRICANTE FOREIGN KEY (COD_FABRICANTE)
    REFERENCES TB_FABRICANTE (COD_FABRICANTE),
  CONSTRAINT FK_MODELO_PAIS_PROD FOREIGN KEY (COD_PAIS_PRODUCAO)
    REFERENCES TB_PAIS (COD_PAIS)
);

-- LOJA (filiais)
CREATE TABLE TB_LOJA (
  COD_LOJA   NUMERIC(6)       SERIAL PRIMARY KEY,
  NOME_LOJA  VARCHAR(80)    NOT NULL,
  CIDADE     VARCHAR(60)    NOT NULL,
  ESTADO     CHAR(2)         NOT NULL,
  CNPJ       CHAR(14)        NOT NULL,
  CONSTRAINT UK_TB_LOJA_CNPJ UNIQUE (CNPJ)
);

-- VENDEDOR
CREATE TABLE TB_VENDEDOR (
  COD_VENDEDOR    NUMERIC(6)     SERIAL PRIMARY KEY,
  NOME_VENDEDOR   VARCHAR(80)   NOT NULL,
  EMAIL           VARCHAR(120)  NOT NULL,
  TELEFONE        VARCHAR(20)   NOT NULL,
  COD_LOJA        NUMERIC(6)      NOT NULL,
  DT_ADMISSAO     DATE           NOT NULL,
  COMISSAO_PCT    NUMERIC(5,2)    NOT NULL,
  CONSTRAINT UK_TB_VENDEDOR_EMAIL UNIQUE (EMAIL),
  CONSTRAINT FK_VENDEDOR_LOJA FOREIGN KEY (COD_LOJA)
    REFERENCES TB_LOJA (COD_LOJA),
  CONSTRAINT CK_TB_VENDEDOR_COMIS CHECK (COMISSAO_PCT BETWEEN 0 AND 20)
);

-- CLIENTE
CREATE TABLE TB_CLIENTE (
  COD_CLIENTE   NUMERIC(8)  SERIAL PRIMARY KEY,
  NOME_CLIENTE  VARCHAR(80)   NOT NULL,
  CPF           CHAR(11)       NOT NULL,
  EMAIL         VARCHAR(120)  NOT NULL,
  TELEFONE      VARCHAR(20)   NOT NULL,
  CIDADE        VARCHAR(60)   NOT NULL,
  ESTADO        CHAR(2)        NOT NULL,
  DT_CADASTRO   DATE           NOT NULL,
  CONSTRAINT UK_TB_CLIENTE_CPF UNIQUE (CPF),
  CONSTRAINT UK_TB_CLIENTE_EMAIL UNIQUE (EMAIL)
);

-- CARRO (unidade física em estoque / vendido)
CREATE TABLE TB_CARRO (
  COD_CARRO        NUMERIC(10)    SERIAL PRIMARY KEY,
  VIN              VARCHAR(17)   NOT NULL,
  COD_MODELO       NUMERIC(8)      NOT NULL,
  ANO_FABRICACAO   NUMERIC(4)      NOT NULL,
  KM              NUMERIC(10)     NOT NULL,
  PRECO_TABELA     NUMERIC(12,2)   NOT NULL,
  STATUS           VARCHAR(20)   NOT NULL,
  COD_LOJA         NUMERIC(6)      NOT NULL,
  CONSTRAINT UK_TB_CARRO_VIN UNIQUE (VIN),
  CONSTRAINT FK_CARRO_MODELO FOREIGN KEY (COD_MODELO)
    REFERENCES TB_MODELO (COD_MODELO),
  CONSTRAINT FK_CARRO_LOJA FOREIGN KEY (COD_LOJA)
    REFERENCES TB_LOJA (COD_LOJA),
  CONSTRAINT CK_TB_CARRO_STATUS CHECK (STATUS IN ('EM_ESTOQUE','RESERVADO','VENDIDO')),
  CONSTRAINT CK_TB_CARRO_ANO CHECK (ANO_FABRICACAO BETWEEN 1980 AND 2100),
  CONSTRAINT CK_TB_CARRO_KM CHECK (KM >= 0),
  CONSTRAINT CK_TB_CARRO_PRECO CHECK (PRECO_TABELA >= 0)
);

-- VENDA (cabeçalho)
CREATE TABLE TB_VENDA (
  COD_VENDA     NUMERIC(10)   SERIAL PRIMARY KEY,
  COD_LOJA      NUMERIC(6)      NOT NULL,
  COD_VENDEDOR  NUMERIC(6)      NOT NULL,
  COD_CLIENTE   NUMERIC(8)      NOT NULL,
  DT_VENDA      DATE           NOT NULL,
  FORMA_PAGTO   VARCHAR(20)   NOT NULL,
  TOTAL_VENDA   NUMERIC(12,2)   NOT NULL,
  CONSTRAINT FK_VENDA_LOJA FOREIGN KEY (COD_LOJA)
    REFERENCES TB_LOJA (COD_LOJA),
  CONSTRAINT FK_VENDA_VENDEDOR FOREIGN KEY (COD_VENDEDOR)
    REFERENCES TB_VENDEDOR (COD_VENDEDOR),
  CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (COD_CLIENTE)
    REFERENCES TB_CLIENTE (COD_CLIENTE),
  CONSTRAINT CK_TB_VENDA_PAGTO CHECK (FORMA_PAGTO IN ('PIX','CARTAO','BOLETO','FINANCIAMENTO','TED')),
  CONSTRAINT CK_TB_VENDA_TOTAL CHECK (TOTAL_VENDA >= 0)
);

-- VENDA_ITEM (itens da venda; aqui 1 carro por item)
CREATE TABLE TB_VENDA_ITEM (
  COD_ITEM     NUMERIC(10)     SERIAL PRIMARY KEY,
  COD_VENDA    NUMERIC(10)     NOT NULL,
  COD_CARRO    NUMERIC(10)     NOT NULL,
  PRECO_VENDA  NUMERIC(12,2)   NOT NULL,
  DESCONTO     NUMERIC(12,2)   NOT NULL,
  IMPOSTO      NUMERIC(12,2)   NOT NULL,
  TOTAL_ITEM   NUMERIC(12,2)   NOT NULL,
  CONSTRAINT FK_ITEM_VENDA FOREIGN KEY (COD_VENDA)
    REFERENCES TB_VENDA (COD_VENDA),
  CONSTRAINT FK_ITEM_CARRO FOREIGN KEY (COD_CARRO)
    REFERENCES TB_CARRO (COD_CARRO),
  CONSTRAINT UK_ITEM_CARRO_UNICO UNIQUE (COD_CARRO),
  CONSTRAINT CK_ITEM_VALORES CHECK (
    PRECO_VENDA >= 0 AND DESCONTO >= 0 AND IMPOSTO >= 0 AND TOTAL_ITEM >= 0
  )
);